// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table media_metadata {
  id bigint [primary key]
  caption varchar(255)
  post_id bigint
}

Table location {
  id bigint [primary key]
  caption varchar(255)
  lat double
  lon double
  geohash int
  create_at timestamp
  created_by bigint 
}

Table post {
  id bigint [primary key]
  text varchar(1000)
  location_id bigint
  create_at timestamp
  created_by bigint 
}

Ref: post.location_id > location.id
Ref: post.id < media_metadata.post_id
