// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table media_metadata {
  id bigint [primary key]
  caption varchar(255)
  post_id bigint
}

Table location {
  id bigint [primary key]
  caption varchar(255)
  lat double
  lon double
  rate_total bigint [note: 'For easy refresh and calculation avarage value']
  rates_count bigint
  create_at timestamp
  created_by bigint 
}

Table post {
  id bigint [primary key]
  text varchar(1000)
  location_id bigint
  rate_total bigint [note: 'For easy refresh and calculation avarage value']
  rates_count bigint
  create_at timestamp
  created_by bigint 
}

Table comment {
  id bigint [primary key]
  text varchar(1000)
  post_id bigint
  create_at timestamp
  created_by bigint 
}

Table rate {
  post_id bigint [primary key]
  created_by bigint [primary key]
  value int
  create_at timestamp
}

Table subscription {
  subscribed_by bigint [primary key]
  subscribed_on bigint [primary key]
}

Table user [note: 'In third party SSO service'] {
  id bigint [primary key]
  name varchar(255)
}

Ref: location.created_by > user.id
Ref: post.created_by > user.id
Ref: comment.created_by > user.id
Ref: rate.created_by > user.id

Ref: post.location_id > location.id
Ref: post.id < media_metadata.post_id
Ref: post.id < comment.post_id
Ref: post.id < rate.post_id

Ref: subscription.subscribed_by > user.id
Ref: subscription.subscribed_on > user.id
