// Replication:
// - async master-slave
// - replication factor 2
// Sharding
// - key based by subscriber id

Table subscription {
  subscribed_by bigint [primary key]
  subscribed_on bigint [primary key]
}

Table user [note: 'For easy refreshing and calculation statistic and detecting celebrities'] {
  id bigint [primary key]
  total_subscriptions bigint
  total_followers bigint
}

Ref: subscription.subscribed_by > user.id
Ref: subscription.subscribed_on > user.id
